
DROP TABLE IF EXISTS S275;

-- next

CREATE TABLE S275 (
	AcademicYear varchar(500) NULL,
	Area varchar(500) NULL,
	County varchar(500) NULL,
	District varchar(500) NULL,
	CountyAndDistrictCode varchar(500) NULL,
	LastName varchar(500) NULL,
	FirstName varchar(500) NULL,
	MiddleName varchar(500) NULL,
	CertificateNumber varchar(500) NULL,
	Birthdate varchar(500) NULL,
	Sex varchar(500) NULL,
	Hispanic varchar(500) NULL,
	Race varchar(500) NULL,
	HighestDegree varchar(500) NULL,
	HighestDegreeYear varchar(500) NULL,
	AcademicCredits varchar(500) NULL,
	InServiceCredits varchar(500) NULL,
	ExcessCredits varchar(500) NULL,
	NonDegreeCredits varchar(500) NULL,
	CertYearsOfExperience varchar(500) NULL,
	StaffMixFactor varchar(500) NULL,
	FTEHours varchar(500) NULL,
	FTEDays varchar(500) NULL,
	CertificatedFTE varchar(500) NULL,
	ClassifiedFTE varchar(500) NULL,
	CertificatedBase varchar(500) NULL,
	ClassifiedBase varchar(500) NULL,
	OtherSalary varchar(500) NULL,
	TotalFinalSalary varchar(500) NULL,
	ActualAnnualInsurance varchar(500) NULL,
	ActualAnnualMandatory varchar(500) NULL,
	CBRTNCode varchar(500) NULL,
	ClassificationFlag varchar(500) NULL,
	CertifiedFlag varchar(500) NULL,
	NationalBoardCertExpirationDate varchar(500) NULL,
	RecordNumber varchar(500) NULL,
	ProgramCode varchar(500) NULL,
	ActivityCode varchar(500) NULL,
	DutyArea varchar(500) NULL,
	DutyRoot varchar(500) NULL,
	DutySuffix varchar(500) NULL,
	Grade varchar(500) NULL,
	Building varchar(500) NULL,
	AssignmentPercent varchar(500) NULL,
	AssignmentFTEDesignation varchar(500) NULL,
	AssignmentSalaryTotal varchar(500) NULL,
	AssignmentHoursPerYear varchar(500) NULL,
	Major varchar(500) NULL,
	TwoDigitYear varchar(500) NULL,
	FileType varchar(500) NULL
)
