

# Load the raw S275 data and other source tables
python -c "import S275; S275.load()"

# Create some seed tables
dbt seed

# Run all the transforms. Don't stop after this step! Some fields will be incorrect
# because they depend on data generated by scripts in the next step. Keep going.
dbt run

# Now run scripts to populate external 'ext' tables that couldn't be created in SQL:
python -c "import S275; S275.create_ext_teachermobility_distance()"
python -c "import S275; S275.create_ext_school_leadership_broad()"

# Re-run the specific transforms that depend on the above re-created tables.
dbt run -m source:ext+
