
version: 2

sources:
  - name: sources
    description: raw source data
    # by default, schema is set to name of source. we use schema from our target (defined in profiles.yml)
    schema: "{{ target.schema }}"
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
      - name: Duty_Codes
      - name: Raw_School_Base
      - name: Raw_School_Fields
      - name: Raw_S275
  - name: ext
    description: data created outside SQL and the DAG, but is part of the DAG
    # by default, schema is set to name of source. we use schema from our target (defined in profiles.yml)
    schema: "{{ target.schema }}"
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
      - name: Ext_TeacherMobility_Distance
      - name: Ext_SchoolLeadership_Broad
      - name: Ext_DutyList

models:
  - name: Dim_Staff
    description: '{{ doc("Dim_Staff") }}'
  - name: Dim_School
    description: '{{ doc("Dim_School") }}'
  - name: Fact_Assignment
    description: '{{ doc("Fact_Assignment") }}'
  - name: Fact_Career
    description: '{{ doc("Fact_Career") }}'
    columns:
      - name: RaceEthOSPI
        description: most recent race value in the S-275 for this individual
      - name: Sex
        description: most recent 'sex' value in the S-275 for this individual
      - name: FirstYear
        description: first year that individual is present in S-275 data
      - name: MostRecentYear
        description: most recent year that individual is present in S-275 data
      - name: TotalActiveYearsWA
        description: total years this person is in the S-275 data
      - name: NumDistrictsWorked
        description: number of districts where this person was ever employed
      - name: NumSchoolsWorked
        description: number of schools where this person was ever employed
      - name: NumDistinctDutyRoots
        description: number of distinct DutyRoot codes this person ever had
      - name: DutyList
        description: comma-sep list of all of this individual's duty descriptions, in chronological order
      - name: TeacherFirstYear
        description: the first year that this individual was a teacher
      - name: TeacherLastYear
        description: the last year that this individual was a teacher
      - name: TeacherNumYears
        description: number of years this individual was a teacher
      - name: APOrPrincipalFirstYear
        description: the first year that this individual was an Asst Prin or Principal
      - name: APOrPrincipalLastYear
        description: the last year that this individual was an Asst Prin or Principal
      - name: APOrPrincipalNumYears
        description: number of years this individual was an Asst Prin or Principal
      - name: TeacherToAPOrPrincipal
        description: set to 1 if individual was a teacher who then became a principal
  - name: Fact_SchoolTeacher
    description: '{{ doc("Fact_SchoolTeacher") }}'
  - name: Fact_SchoolPrincipal
    description: '{{ doc("Fact_SchoolPrincipal") }}'
  - name: Fact_TeacherMobility
    description: '{{ doc("Fact_TeacherMobility") }}'
  - name: Fact_PrincipalMobility
    description: '{{ doc("Fact_PrincipalMobility") }}'
  - name: Fact_TeacherCohort
    description: '{{ doc("Fact_TeacherCohort") }}'
  - name: Fact_TeacherCohortMobility
    description: '{{ doc("Fact_TeacherCohortMobility") }}'
  - name: Fact_PrincipalCohort
    description: '{{ doc("Fact_PrincipalCohort") }}'
  - name: Fact_PrincipalCohortMobility
    description: '{{ doc("Fact_PrincipalCohortMobility") }}'
  - name: S275
    description: '{{ doc("S275") }}'
